/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check whether the API process is alive
         * @description A dependency-free probe for process supervisors. This operation is public, read-only, and has no side effects.
         */
        get: operations["getLiveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check required service dependencies
         * @description Checks Postgres and Redis with short timeouts. Returns HTTP 200 when both dependencies respond and HTTP 503 otherwise. This public, read-only operation has no side effects.
         */
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List broker connections
         * @description Returns every broker connection with its sync state. Token material is never included. Read-only, no side effects.
         */
        get: operations["listConnections"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/connections/saxo/authorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Start the Saxo OAuth authorization
         * @description Creates a single-use state value and redirects the browser to SaxoBank's authorization page (authorization code grant). Side effect: stores the state for 15 minutes, server-side and in an HttpOnly cookie that the callback checks. Without SAXO_APP_KEY and SAXO_APP_SECRET it redirects back to the connections page with `error=not_configured`.
         */
        get: operations["startSaxoAuthorization"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/connections/saxo/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Complete the Saxo OAuth authorization
         * @description Redirect target registered in the Saxo app. Validates the state against the stored one and the browser's state cookie, exchanges the code for tokens, stores them encrypted, and redirects the browser back to the connections page with a `connected` parameter, or an `error` code: denied, missing_code, other_browser, invalid_state or exchange_failed.
         */
        get: operations["completeSaxoAuthorization"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/connections/ibkr": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Connect Interactive Brokers through the Flex Web Service
         * @description Stores the Flex token encrypted together with the query id and the token's expiry, then queues the first refresh (statement pull, FX, ingest, prices, PnL rebuild). There is no OAuth: the token is generated in Client Portal under Performance & Reports, Flex Queries. Reconnecting with a new token replaces the stored one. Returns 400 when the token or query id is missing or malformed.
         */
        post: operations["connectIbkr"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/connections/{connection_id}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Queue a broker refresh
         * @description Queues a Celery task that pulls the broker's accounts, positions, balances and history, maps them into the ledger, then syncs prices and FX and rebuilds the PnL tables, so the dashboard reflects the latest broker data. Returns 404 for an unknown connection and 503 when the task queue is unavailable.
         */
        post: operations["queueConnectionSync"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ledger/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List ledger transactions
         * @description Paged, filtered ledger rows (trades, dividends, fees, cash flows). Read-only. `kinds` is a comma-separated list of ledger kinds; unknown kinds are ignored.
         */
        get: operations["listTransactions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List positions
         * @description Holding episodes from the positions table (rebuilt from the ledger after every ingest), open and closed, with split-adjusted average prices, dividends, return, ROI and annualized return. Open positions are valued at the latest broker snapshot. Read-only.
         */
        get: operations["listPositions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/positions/{position_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Position detail
         * @description One position: share counts, returns in the instrument and base currency, its trades, a daily series of split-adjusted quantity, close and market value over the holding, and up to five years of daily closes for price context. Read-only.
         */
        get: operations["getPositionDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List portfolios
         * @description One card per portfolio: broker cash and total value from the latest snapshot, plus the number and value of open positions derived from the ledger. Read-only.
         */
        get: operations["listPortfolios"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolios/{portfolio_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update portfolio settings
         * @description Sets the custom display name used throughout the app. Send null or an empty string to go back to the broker-provided name. reporting_start_date applies from the beginning of that day across reporting, positions and activity; null restores full history. Omitted fields stay unchanged. Future dates are rejected. Retains the underlying ledger and original acquisition costs. Returns 404 for an unknown portfolio.
         */
        patch: operations["updatePortfolio"];
        trace?: never;
    };
    "/api/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List orders
         * @description Every broker order known to the app, working and historical, one row per order in its latest state. Working orders first, then newest placed first. Read-only.
         */
        get: operations["listOrders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ledger/cash-movements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List deposits, withdrawals, transfers and conversions
         * @description External cash flows and internal transfers between the client's currency accounts. The two legs of a transfer are merged into one row; a cross-currency pair is reported as a conversion with its implied rate.
         */
        get: operations["listCashMovements"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List UI preferences
         * @description Every stored preference, such as the saved default filters per page. Read-only.
         */
        get: operations["listPreferences"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/preferences/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Save a UI preference
         * @description Stores the value under the key, replacing any previous value. Used to save a page's default filters.
         */
        put: operations["savePreference"];
        post?: never;
        /**
         * Delete a UI preference
         * @description Removes the stored value so the page falls back to its built-in defaults. 404 when nothing is stored.
         */
        delete: operations["deletePreference"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prices/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Price coverage per security
         * @description Which source each security's daily prices come from, how far they reach, and the last error. Read-only.
         */
        get: operations["listPriceStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Daily prices of a security
         * @description Split-adjusted daily OHLCV in the instrument currency, oldest first, optionally limited to a date range.
         */
        get: operations["listDailyPrices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fx/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * FX coverage per currency
         * @description Every currency the ledger or securities use, with the stored rate coverage. Read-only.
         */
        get: operations["listFxStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fx": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Daily FX series
         * @description ECB reference rates crossed through EUR into the base currency, one row per published day, oldest first. Gaps (weekends, holidays) are carried forward by the engine, not stored.
         */
        get: operations["listFxRates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dashboard from calculated portfolio results
         * @description Read-only snapshot of NAV history, daily PnL, FX attribution including cash, portfolio returns, five highest and lowest contributors, and recorded reconciliation findings. Uses the latest shared day of portfolios with calculated returns, today included once it has market observations (flagged as intraday); missing coverage is reported in warnings. Totals are unavailable for mixed base currencies. Does not sync brokers or rebuild data. Uses the same access policy as other report endpoints; no additional endpoint-specific authentication.
         */
        get: operations["getDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/pnl": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Daily position attribution
         * @description One row per position per calendar day: quantities, carried price and FX, market value and the decomposition of the day's PnL into price, FX, interaction, dividend, interest and cost effects. Cash balances per currency are positions too. Paged; filters and sort are query parameters. Read-only.
         */
        get: operations["listPnlRows"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/portfolio-days": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Unitized portfolio series
         * @description NAV, external flows, lifetime cumulative net cash additions and monetary return, daily PnL, units, unit price, cumulative return and drawdown per calendar day. Cash additions and monetary return retain history before date filters and each portfolio's reporting start. Without portfolio_id (or with 0) all portfolios are unitized together as 'Total'. Read-only.
         */
        get: operations["listPortfolioDays"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reconciliation/issues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Issues recorded by the last rebuild
         * @description Data-quality findings of the PnL engine: missing or stale prices, missing FX, inferred splits, and days where the engine NAV differs from the broker's reported value, split into ECB-vs-broker FX, cash and securities where the broker's FX rates are known. Read-only.
         */
        get: operations["listReconciliationIssues"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/rebuild": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rebuild the derived PnL tables
         * @description Runs the SQL engine for every portfolio from the ledger, prices and FX, replacing pnl_days, portfolio_days and reconciliation_issues. Synchronous; takes some seconds per portfolio.
         */
        post: operations["rebuildPnl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/reporting-currency": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Reporting currency
         * @description The currency every portfolio is booked and reported in, the currencies it can be changed to, and whether a recalculation after a change is still running. Read-only.
         */
        get: operations["getReportingCurrency"];
        /**
         * Change the reporting currency
         * @description Stores the reporting currency and queues the recalculation: FX rates crossed into it, every broker ledger re-mapped from its stored payloads (no broker requests), and the PnL rebuild. Reports show mixed currencies until it finishes; poll the GET endpoint for `pending`. 400 for a currency without ECB rates, or one a connected broker cannot be booked in (Saxo books in its client currency).
         */
        put: operations["setReportingCurrency"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CashBalance */
        CashBalance: {
            /** @example USD */
            currency: string;
            /** @description Cash held in that currency account, in the account currency. */
            amount: string;
        };
        /** CashMovementRow */
        CashMovementRow: {
            id: number;
            /** Format: date */
            trade_date: string;
            value_date: string | null;
            /**
             * @description deposit, withdrawal, transfer, or conversion.
             * @example conversion
             */
            kind: string;
            portfolio_name: string;
            from_account: string | null;
            from_currency: string | null;
            /** @description Negative amount leaving the source account. */
            from_amount: string | null;
            to_account: string | null;
            to_currency: string | null;
            to_amount: string | null;
            /** @description Units of target currency per unit of source currency for conversions. */
            rate: string | null;
            base_currency: string;
            amount_base: string | null;
            description: string | null;
        };
        /** CashMovementsResponse */
        CashMovementsResponse: {
            data: components["schemas"]["CashMovementRow"][];
            meta: components["schemas"]["PageMeta"];
        };
        /** ConnectionCreatedResponse */
        ConnectionCreatedResponse: {
            /**
             * @description The stored connection.
             * @example 2
             */
            connection_id: number;
            /** @description Celery task of the first refresh, or null when the queue is down. */
            task_id: string | null;
        };
        /** ConnectionStatus */
        ConnectionStatus: {
            /**
             * @description Connection identifier.
             * @example 1
             */
            id: number;
            /**
             * @description Broker key.
             * @example saxo
             */
            broker: string;
            /**
             * @description Broker environment, live or sim.
             * @example live
             */
            environment: string;
            /** @description Broker-side client key once the first sync ran. */
            client_key: string | null;
            /** @description Client name reported by the broker. */
            client_name: string | null;
            /**
             * @description Client default currency reported by the broker.
             * @example EUR
             */
            base_currency: string | null;
            /**
             * @description connected, expired, or error.
             * @example connected
             */
            status: string;
            /** @description Report query id for brokers that pull reports (IBKR Flex). */
            query_id?: string | null;
            /**
             * @description Active broker accounts found by the last sync.
             * @example 2
             */
            account_count: number;
            /**
             * Format: date-time
             * @description When the current access token expires.
             */
            access_token_expires_at: string;
            /** @description When the refresh token expires, if known. */
            refresh_token_expires_at: string | null;
            /** @description Start of the most recent sync. */
            last_sync_started_at: string | null;
            /** @description End of the most recent sync. */
            last_sync_finished_at: string | null;
            /** @description Error message of the most recent sync, if it failed. */
            last_sync_error: string | null;
            /** @description End of the most recent successful sync. */
            last_success_finished_at: string | null;
            /**
             * Format: date-time
             * @description When the connection was first authorized.
             */
            created_at: string;
        };
        /** ConnectionsResponse */
        ConnectionsResponse: {
            /** @description All broker connections, without token material. */
            connections: components["schemas"]["ConnectionStatus"][];
        };
        /** CurrencyOption */
        CurrencyOption: {
            /** @example EUR */
            code: string;
            /** @description Whether the currency can be chosen now. */
            allowed: boolean;
            /** @description Why it cannot be chosen, when it cannot. */
            reason?: string | null;
        };
        /** DailyPriceRow */
        DailyPriceRow: {
            /** Format: date */
            price_date: string;
            open: string | null;
            high: string | null;
            low: string | null;
            close: string;
            volume: string | null;
            currency: string | null;
            source: string;
        };
        /** DailyPricesResponse */
        DailyPricesResponse: {
            security_id: number;
            data: components["schemas"]["DailyPriceRow"][];
        };
        /** DashboardFx */
        DashboardFx: {
            currency: string;
            /** @description Summed FX effect in base currency, including cash. */
            effect: string;
        };
        /** DashboardNavPoint */
        DashboardNavPoint: {
            /** Format: date */
            day: string;
            nav: string;
        };
        /** DashboardPortfolio */
        DashboardPortfolio: {
            reporting_start_date?: string | null;
            portfolio_id: number;
            portfolio_name: string;
            base_currency: string;
            first_day: string | null;
            /** @description Latest calculated day available for this portfolio. */
            last_day: string | null;
            nav: string | null;
            daily_pnl: string | null;
            daily_return_pct: string | null;
            cumulative_return_pct: string | null;
        };
        /** DashboardResponse */
        DashboardResponse: {
            /** @description Latest shared valuation day, today included, with market observations or account activity; base-currency cash-only days need neither. Null when totals are unavailable. */
            as_of: string | null;
            /** @description True when as_of is today: its closes are the latest intraday prices until the markets close. */
            intraday: boolean;
            base_currency: string | null;
            nav: string | null;
            daily_pnl: string | null;
            /** @description Summed PnL / summed prior NAV, as a fraction. */
            daily_return_pct: string | null;
            fx_effect_base: string | null;
            /** @description Data-quality findings from the latest rebuilds within each reporting period. */
            issue_count: number;
            series: components["schemas"]["DashboardNavPoint"][];
            portfolios: components["schemas"]["DashboardPortfolio"][];
            fx_by_currency: components["schemas"]["DashboardFx"][];
            top: components["schemas"]["PnlRow"][];
            bottom: components["schemas"]["PnlRow"][];
            warnings: string[];
        };
        /** DependencyStatus */
        DependencyStatus: {
            /** @description Dependency state: ok or unavailable. */
            status: string;
            /** @description Safe failure summary when unavailable. */
            detail?: string | null;
        };
        /** EngineStatusRow */
        EngineStatusRow: {
            portfolio_id: number;
            portfolio_name: string;
            first_day: string | null;
            last_day: string | null;
            position_rows: number;
            issues: number;
        };
        /** ErrorResponse */
        ErrorResponse: {
            /**
             * @description HTTP status code.
             * @example 400
             */
            status_code: number;
            /**
             * @description Stable machine-readable error category.
             * @example bad_request
             */
            error: string;
            /**
             * @description Human-readable explanation safe to show to a caller.
             * @example The request could not be processed.
             */
            detail: string;
            /**
             * @description Identifier for correlating the response with server logs.
             * @example 01JEXAMPLE1234567890
             */
            request_id: string;
        };
        /** FxRateRow */
        FxRateRow: {
            /** Format: date */
            rate_date: string;
            /** @description Base currency per one unit of the currency. */
            rate: string;
            /** @description ecb or identity. */
            source: string;
        };
        /** FxSeriesResponse */
        FxSeriesResponse: {
            base_currency: string;
            currency: string;
            data: components["schemas"]["FxRateRow"][];
        };
        /** FxStatusResponse */
        FxStatusResponse: {
            data: components["schemas"]["FxStatusRow"][];
        };
        /** FxStatusRow */
        FxStatusRow: {
            /** @example EUR */
            base_currency: string;
            /** @example USD */
            currency: string;
            /** @description First ledger date of any portfolio in this base currency. */
            first_needed: string | null;
            first_date: string | null;
            last_date: string | null;
            /** @description Published days stored. */
            days: number;
            /** @description Base currency per one unit of the currency. */
            last_rate: string | null;
        };
        /** IbkrConnectRequest */
        IbkrConnectRequest: {
            /** @description Flex Web Service token generated in Client Portal. */
            token: string;
            /**
             * @description Id of the Activity Flex Query to pull.
             * @example 123456
             */
            query_id: string;
            /** @description When the token expires, as chosen when it was generated; a year from now when omitted. */
            expires_at?: string | null;
        };
        /** IssueFxRate */
        IssueFxRate: {
            currency: string;
            /** @description Reporting currency per unit, the ECB rate the engine valued the day at. */
            ecb_rate: string;
            /** @description Date of that ECB rate (forward-filled over non-fixing days). */
            ecb_rate_date: string | null;
            /** @description Reporting currency per unit at the broker's own rate; null when the broker's rate is unknown. */
            broker_rate: string | null;
            broker_rate_date: string | null;
            /** @description Currency the broker quotes its own rate in (IBKR: the account base, crossed into the reporting currency with the ECB rate its NAV is converted with). */
            broker_quote_currency: string | null;
            /** @description The broker's rate as stated: quote currency per unit. */
            broker_quote_rate: string | null;
            /** @description Engine holdings in this currency (securities and cash), local amount. */
            value_local: string;
            /** @description value_local x (ecb_rate - broker_rate): this currency's part of the issue's gap_fx. */
            gap_fx: string | null;
        };
        /** IssueRow */
        IssueRow: {
            id: number;
            portfolio_id: number;
            portfolio_name: string;
            /** Format: date */
            day: string;
            /** @example nav_mismatch */
            kind: string;
            security_id: number | null;
            security_name: string | null;
            full_ticker: string | null;
            currency: string | null;
            amount: string | null;
            message: string;
            /** Format: date-time */
            created_at: string;
            /** @description Broker of the portfolio's connection, e.g. ibkr or saxo. */
            broker?: string | null;
            /** @description NAV mismatches: part of the difference from valuing holdings at ECB rates instead of the broker's own FX rates. Null when the broker's rates are not known for every held currency. */
            gap_fx?: string | null;
            /** @description NAV mismatches: engine cash minus broker cash, both at the broker's FX rates. */
            gap_cash?: string | null;
            /** @description NAV mismatches: engine securities minus broker securities at the broker's FX rates (prices and quantities). gap_fx + gap_cash + gap_securities equals amount. */
            gap_securities?: string | null;
            /** @description NAV mismatches: ECB and broker FX rate per held currency, largest effect first. */
            fx_rates?: components["schemas"]["IssueFxRate"][];
        };
        /** IssuesResponse */
        IssuesResponse: {
            data: components["schemas"]["IssueRow"][];
        };
        /** OrderRow */
        OrderRow: {
            id: number;
            broker_order_id: string;
            portfolio_id: number;
            portfolio_name: string;
            /**
             * @description Broker account id and currency.
             * @example 1234567/2 (USD)
             */
            account_label: string | null;
            /** @description Null when the instrument is unknown to the securities table. */
            security_id: number | null;
            security_name: string | null;
            /**
             * @description ticker:MIC when known.
             * @example ROKU:XNAS
             */
            full_ticker: string | null;
            asset_type: string | null;
            /** @description Symbol as the broker reported it on the order. */
            instrument_symbol: string | null;
            /**
             * @description working, filled, cancelled, expired, rejected or other.
             * @example working
             */
            status: string;
            /**
             * @description The broker's own status word.
             * @example Working
             */
            broker_status: string | null;
            /** @description True when the broker listed the order as working at the latest sync. */
            is_open: boolean;
            /** @description buy or sell. */
            buy_sell: string | null;
            /** @example Limit */
            order_type: string | null;
            /** @example GoodTillCancel */
            duration: string | null;
            quantity: string | null;
            filled_quantity: string | null;
            /** @description Limit or stop price in the instrument currency. */
            price: string | null;
            average_fill_price: string | null;
            currency: string | null;
            placed_at: string | null;
            last_activity_at: string | null;
            expires_at: string | null;
            /** @description StandAlone, IfDoneMaster, IfDoneSlave or Oco. */
            order_relation: string | null;
        };
        /** OrdersResponse */
        OrdersResponse: {
            data: components["schemas"]["OrderRow"][];
            meta: components["schemas"]["PageMeta"];
        };
        /** PageMeta */
        PageMeta: {
            /**
             * @description Rows matching the filters before paging.
             * @example 3120
             */
            total: number;
            /**
             * @description 1-based page number.
             * @example 1
             */
            page: number;
            /**
             * @description Rows per page.
             * @example 100
             */
            per_page: number;
            /**
             * @description Applied sort column.
             * @example trade_date
             */
            order_by: string;
            /**
             * @description asc or desc.
             * @example desc
             */
            order: string;
        };
        /** PnlResponse */
        PnlResponse: {
            data: components["schemas"]["PnlRow"][];
            meta: components["schemas"]["PageMeta"];
        };
        /** PnlRow */
        PnlRow: {
            /** Format: date */
            day: string;
            portfolio_id: number;
            portfolio_name: string;
            /**
             * @description security or cash.
             * @example security
             */
            position_kind: string;
            /**
             * @description Stable key of the position within the portfolio.
             * @example sec:12
             */
            position_key: string;
            security_id: number | null;
            security_name: string | null;
            /**
             * @description ticker:MIC, or the currency for cash.
             * @example ROKU:XNAS
             */
            full_ticker: string | null;
            /** @description Instrument currency, or the cash currency. */
            currency: string;
            base_currency: string;
            /**
             * @description long or short.
             * @example long
             */
            position_type: string;
            /** @description Held at the close, on the split-adjusted basis of the price history. */
            quantity: string;
            quantity_prev: string;
            /** @description Net traded on the day, same basis. */
            trade_quantity: string;
            /** @description Raw ledger quantity times this equals quantity. */
            basis_factor: string;
            /** @description Carried close in the instrument currency; 1 for cash. */
            price: string | null;
            price_change: string | null;
            /** @description Observation date of the carried price. */
            price_date: string | null;
            /** @description close, ledger or cash. */
            price_source: string | null;
            /** @description Base currency per unit of the instrument currency. */
            fx: string | null;
            fx_change: string | null;
            /** @description Volume-weighted price of the day's trades. */
            execution_price: string | null;
            execution_fx: string | null;
            market_value_base: string;
            market_value_local: string;
            prev_market_value_base: string;
            /** @description Cost of the day's trades (buys positive), ex costs. */
            trade_flow_base: string;
            trade_flow_local: string;
            /** @description All base money into the position; daily_pnl = ΔMV - flow exactly. */
            flow_base: string;
            price_effect_base: string;
            price_effect_local: string;
            fx_effect_base: string;
            interaction_effect_base: string;
            /** @description Dividends and lending income booked on the day. */
            dividend_effect_base: string;
            dividend_effect_local: string;
            interest_effect_base: string;
            /** @description Commissions, fees, taxes and withholding tax (negative). */
            cost_effect_base: string;
            cost_effect_local: string;
            daily_pnl_base: string;
            daily_pnl_local: string;
            /** @description daily_pnl_base over |prior market value|, as a fraction. */
            daily_return_pct: string | null;
            /** @description Local PnL at yesterday's FX over |prior value|. */
            constant_currency_return_pct: string | null;
            /** @description Running sum of daily_pnl_base for the position. */
            total_pnl_base: string;
            total_pnl_local: string;
        };
        /** PortfolioAccount */
        PortfolioAccount: {
            /** @description Internal account id, used by the transactions `account` filter. */
            id: number;
            /**
             * @description Broker account number.
             * @example 1234567/2
             */
            account_id: string | null;
            currency: string | null;
            /**
             * @description Account number and currency.
             * @example 1234567/2 (USD)
             */
            label: string;
            active: boolean;
        };
        /** PortfolioCard */
        PortfolioCard: {
            id: number;
            /** @description Name to show: the custom display name when set, else the broker name. */
            name: string;
            /** @description Name reported by the broker. */
            broker_name: string;
            /** @description User-chosen name, null when the broker name is used. */
            display_name: string | null;
            /** @description Inclusive reporting boundary; null means full history. */
            reporting_start_date?: string | null;
            /** @example EUR */
            base_currency: string;
            /** @description saxo or ibkr; null when the portfolio has no connection. */
            broker: string | null;
            /** @description live or sim. */
            environment: string | null;
            /** @description connected, expired or error. */
            connection_status: string | null;
            last_sync_finished_at: string | null;
            /** @description Date of the broker snapshot the values come from. */
            snapshot_date: string | null;
            /** @description Number of open holding episodes. */
            open_positions: number;
            /** @description Market value of the open positions in base currency. */
            positions_value_base: string;
            /** @description Broker cash balance across currency accounts, in base currency. */
            cash_base: string | null;
            /** @description Broker total account value in base currency. */
            total_value_base: string | null;
            /** @description Executed trades the broker has not booked to cash yet, in base currency; counted in total_value_base but in neither cash nor positions. Null when the broker reports no such figure. */
            unbooked_base: string | null;
            /** @description total_value_base minus cash_base, positions_value_base and unbooked_base; accrued items and rounding. */
            unexplained_base: string | null;
            /** @description Non-zero cash balances per currency account. */
            cash_by_currency: components["schemas"]["CashBalance"][];
            /** @description Broker accounts behind the portfolio. */
            accounts: components["schemas"]["PortfolioAccount"][];
        };
        /** PortfolioCurrency */
        PortfolioCurrency: {
            portfolio_id: number;
            portfolio_name: string;
            /** @description Currency the portfolio's ledger is booked in. */
            booked_currency: string;
            /** @description Currency of the last PnL rebuild; null before the first. */
            built_currency: string | null;
        };
        /** PortfolioDay */
        PortfolioDay: {
            reporting_start_date?: string | null;
            /** Format: date */
            day: string;
            /** @description 0 for all portfolios together. */
            portfolio_id: number;
            portfolio_name: string;
            base_currency: string;
            /** @description Positions plus cash at the close, in base currency. */
            nav: string;
            positions_value: string;
            cash_value: string;
            nav_prev: string;
            /** @description External flow: deposits minus withdrawals. */
            flow: string;
            /** @description Lifetime deposits minus withdrawals through this day, in base currency, including history before date filters and reporting start. Total sums the portfolios included in that day's NAV. */
            cumulative_cash_additions: string;
            /** @description Lifetime monetary return: NAV minus cumulative_cash_additions. */
            returns_base: string;
            /** @description nav - nav_prev - flow; equals the sum of the positions' daily PnL. */
            daily_pnl: string;
            /** @description Time-weighted daily return, as a fraction. */
            daily_return_pct: string | null;
            /** @description NAV per unit, 100 at inception. */
            unit_price: string;
            units: string;
            cumulative_return_pct: string;
            /** @description Unit price relative to its running peak, as a fraction (≤ 0). */
            drawdown_pct: string;
            /** @description Broker-reported account value on snapshot days. */
            broker_value: string | null;
        };
        /** PortfolioDaysResponse */
        PortfolioDaysResponse: {
            portfolio_id: number;
            data: components["schemas"]["PortfolioDay"][];
            summary: components["schemas"]["SeriesSummary"];
        };
        /** PortfolioUpdate */
        PortfolioUpdate: {
            /**
             * @description Inclusive start of portfolio reporting. Null restores full history; omitted leaves it unchanged.
             * @example 2024-01-01
             */
            reporting_start_date?: string | null;
            /**
             * @description Custom name shown throughout the app. Null or blank restores the broker name.
             * @example Saxo pension
             */
            display_name?: string | null;
        };
        /** PortfoliosResponse */
        PortfoliosResponse: {
            data: components["schemas"]["PortfolioCard"][];
        };
        /** PositionDetail */
        PositionDetail: {
            id: number;
            portfolio_id: number;
            portfolio_name: string;
            security_id: number;
            security_name: string | null;
            /** @example ANET:XNYS */
            full_ticker: string;
            asset_type: string;
            /** @description Instrument currency. */
            currency: string | null;
            base_currency: string;
            position_type: string;
            /** @description open or closed. */
            status: string;
            reporting_start_date?: string | null;
            /** @description Lifetime acquisition cash, negative, in instrument currency. */
            original_cost_local: string;
            /** @description Lifetime acquisition cash, negative, in base currency. */
            original_cost_base: string;
            /**
             * Format: date
             * @description First trade.
             */
            opened: string;
            /** @description The trade that brought the quantity to zero, when closed. */
            closed: string | null;
            current_price: string | null;
            /** @description Date of the broker mark or engine close behind current_price. */
            price_date: string | null;
            shares: components["schemas"]["ShareStats"];
            returns_local: components["schemas"]["ReturnsBlock"];
            returns_base: components["schemas"]["ReturnsBlock"];
            /** @description Oldest first. */
            trades: components["schemas"]["PositionTrade"][];
            /** @description Daily within the reporting period, including carried-in shares; ends at the closing date. */
            series: components["schemas"]["PositionSeriesPoint"][];
            /** @description Daily closes from five years ago (or the opening date, if earlier) to today, for price context. */
            price_history: components["schemas"]["PricePoint"][];
            notes: string[];
        };
        /** PositionRow */
        PositionRow: {
            id: number;
            portfolio_id: number;
            portfolio_name: string;
            security_id: number;
            security_name: string | null;
            /** @example ROKU:XNAS */
            full_ticker: string;
            asset_type: string;
            /** @description Instrument currency. */
            currency: string | null;
            base_currency: string;
            /**
             * @description long or short.
             * @example long
             */
            position_type: string;
            /**
             * @description open or closed.
             * @example open
             */
            status: string;
            reporting_start_date?: string | null;
            /** Format: date */
            opened: string;
            closed: string | null;
            quantity: string;
            /** @description Number of trades within the reporting period. */
            trades: number;
            /** @description Latest broker mark for open positions, or the engine close when that is newer. */
            current_price: string | null;
            /** @description Lifetime split-adjusted average buy price in instrument currency. */
            avg_buy_price: string | null;
            avg_sell_price: string | null;
            /** @description Current market value in base currency; zero when closed. */
            value_base: string;
            /** @description Absolute opening value plus reporting-period purchases and their commissions, fees and taxes. Null when the opening valuation is unavailable. */
            invested_base: string | null;
            /** @description Dividends net of withholding tax plus lending income. */
            dividends_base: string;
            /** @description Commissions, fees and taxes attributed to the position (negative). */
            costs_base: string;
            /** @description Period gain: current value minus opening value plus subsequent trade cash flows, dividends and costs. */
            return_base: string | null;
            /** @description return_base / invested_base, as a fraction. */
            roi_pct: string | null;
            annualized_days_pct: string | null;
            annualized_months_pct: string | null;
            /** @description Share of total account value across portfolios. */
            pct_aum: string | null;
            /** @description Share of the portfolio's open position value. */
            pct_portfolio: string | null;
            notes: string[];
        };
        /** PositionSeriesPoint */
        PositionSeriesPoint: {
            /** Format: date */
            date: string;
            /** @description Split-adjusted shares held at the close of the day. */
            quantity: string;
            /** @description Split-adjusted close in the instrument currency. */
            close: string;
            /** @description quantity times close, in the instrument currency. */
            market_value: string;
        };
        /** PositionTrade */
        PositionTrade: {
            /** Format: date */
            trade_date: string;
            /**
             * @description buy, sell or corporate_action.
             * @example buy
             */
            kind: string;
            /** @description Signed quantity as booked, before later splits. */
            quantity: string;
            /** @description Execution price as booked. */
            price: string | null;
            /** @description Execution price on today's split-adjusted basis. */
            adjusted_price: string | null;
            currency: string;
            amount_local: string;
            amount_base: string;
        };
        /** PositionsResponse */
        PositionsResponse: {
            data: components["schemas"]["PositionRow"][];
            meta: components["schemas"]["PageMeta"];
        };
        /** Preference */
        Preference: {
            /**
             * @description Preference key, <kind>:<name>, e.g. filters:orders.
             * @example filters:orders
             */
            key: string;
            /**
             * @description Filter values by filter name.
             * @example {
             *       "status": "open"
             *     }
             */
            value: {
                [key: string]: string;
            };
            /** Format: date-time */
            updated_at: string;
        };
        /** PreferenceUpdate */
        PreferenceUpdate: {
            /** @description Filter values by filter name; replaces the stored value. */
            value: {
                [key: string]: string;
            };
        };
        /** PreferencesResponse */
        PreferencesResponse: {
            data: components["schemas"]["Preference"][];
        };
        /** PricePoint */
        PricePoint: {
            /** Format: date */
            date: string;
            /** @description Split-adjusted close in the instrument currency. */
            close: string;
        };
        /** PriceStatusResponse */
        PriceStatusResponse: {
            data: components["schemas"]["PriceStatusRow"][];
        };
        /** PriceStatusRow */
        PriceStatusRow: {
            security_id: number;
            security_name: string | null;
            /** @example ROKU:XNAS */
            full_ticker: string;
            asset_type: string;
            /** @description Currency of the stored bars. */
            currency: string | null;
            /**
             * @description saxo, yahoo or none.
             * @example saxo
             */
            source: string;
            yahoo_symbol: string | null;
            /** @description First ledger date of the security. */
            first_needed: string | null;
            /** @description Last ledger date of the security. */
            last_needed: string | null;
            /** @description In the latest broker position snapshot. */
            held: boolean;
            first_price_date: string | null;
            last_price_date: string | null;
            last_close: string | null;
            bars: number;
            last_fetched_at: string | null;
            last_error: string | null;
        };
        /** ReadinessReport */
        ReadinessReport: {
            /** @description ready only when every required dependency responds. */
            status: string;
            checks: {
                [key: string]: components["schemas"]["DependencyStatus"];
            };
        };
        /** RebuildResponse */
        RebuildResponse: {
            portfolios: {
                [key: string]: unknown;
            }[];
            started_at: string;
            finished_at: string;
            status: components["schemas"]["EngineStatusRow"][];
        };
        /** ReportingCurrencySettings */
        ReportingCurrencySettings: {
            /**
             * @description The reporting currency every portfolio is booked in.
             * @example EUR
             */
            currency: string;
            /** @description REPORTING_CURRENCY from the environment, used until one is chosen. */
            default_currency: string;
            /** @description Currencies with ECB reference rates, EUR included. */
            options: components["schemas"]["CurrencyOption"][];
            /** @description True while portfolios are still being re-booked or rebuilt in the currency. */
            pending: boolean;
            portfolios: components["schemas"]["PortfolioCurrency"][];
            /** @description Recalculation task queued by this request, if any. */
            task_id?: string | null;
        };
        /** ReportingCurrencyUpdate */
        ReportingCurrencyUpdate: {
            /** @example EUR */
            currency: string;
        };
        /** ReturnsBlock */
        ReturnsBlock: {
            /** @example USD */
            currency: string;
            /** @description Signed value carried into the reporting period; null if unavailable. */
            opening_value?: string | null;
            /** @description Cash paid for purchases, negative. */
            total_cost: string;
            /** @description Cash received from sales. */
            total_revenue: string;
            /** @description Current market value; zero when closed, null without a valuation. */
            value: string | null;
            /** @description Dividends net of withholding tax plus lending income. */
            dividends: string;
            /** @description Commissions, fees and taxes, negative. */
            costs: string;
            /** @description value - opening_value + total_revenue + total_cost + dividends + costs; null without valuation. */
            return_amount: string | null;
            /** @description return_amount over absolute opening value plus purchases and buy-side costs, as a fraction. */
            roi_pct: string | null;
            annualized_days_pct: string | null;
            annualized_months_pct: string | null;
        };
        /** SeriesSummary */
        SeriesSummary: {
            first_day: string | null;
            last_day: string | null;
            days: number;
            /** @description Return over the returned slice, as a fraction. */
            period_return_pct: string | null;
            /** @description Only after 30 days; calendar-day basis. */
            annualized_return_pct: string | null;
            max_drawdown_pct: string | null;
            nav: string | null;
            unit_price: string | null;
            /** @description Since inception, as a fraction. */
            cumulative_return_pct: string | null;
        };
        /** ShareStats */
        ShareStats: {
            /** @description Number of buy trades. */
            buys: number;
            /** @description Shares bought, on today's split-adjusted basis. */
            shares_bought: string;
            sells: number;
            shares_sold: string;
            /** @description Shares held now; zero when closed. */
            current: string;
        };
        /** StatusResponse */
        StatusResponse: {
            /**
             * @description Current service state.
             * @example ok
             */
            status: string;
        };
        /** SyncQueuedResponse */
        SyncQueuedResponse: {
            /**
             * @description Connection whose sync was queued.
             * @example 1
             */
            connection_id: number;
            /** @description Celery task identifier for the queued sync. */
            task_id: string;
        };
        /** TransactionRow */
        TransactionRow: {
            id: number;
            /** Format: date */
            trade_date: string;
            value_date: string | null;
            /**
             * @description Ledger kind, e.g. trade, dividend, deposit.
             * @example trade
             */
            kind: string;
            portfolio_id: number;
            portfolio_name: string;
            /**
             * @description Broker account id and currency.
             * @example 1234567/2 (USD)
             */
            account_label: string | null;
            security_name: string | null;
            /**
             * @description ticker:MIC when known.
             * @example ROKU:XNAS
             */
            full_ticker: string | null;
            security_currency: string | null;
            quantity: string | null;
            price: string | null;
            currency: string;
            amount_local: string;
            account_currency: string | null;
            amount_account: string | null;
            base_currency: string;
            amount_base: string | null;
            fx_rate_base: string | null;
            description: string | null;
            related_ref: string | null;
            /**
             * @description Executed at the broker but not yet booked: taken from the order audit, replaced by the booked trade.
             * @default false
             */
            provisional: boolean;
        };
        /** TransactionsResponse */
        TransactionsResponse: {
            data: components["schemas"]["TransactionRow"][];
            meta: components["schemas"]["PageMeta"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getLiveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The API process can accept requests. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
            /** @description An unexpected server error using the standard API error envelope. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All required dependencies are ready. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessReport"];
                };
            };
            /** @description An unexpected server error using the standard API error envelope. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description At least one required dependency is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessReport"];
                };
            };
        };
    };
    listConnections: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Broker connections and their state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionsResponse"];
                };
            };
            /** @description An unexpected server error using the standard API error envelope. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    startSaxoAuthorization: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect Response */
            302: {
                headers: {
                    /** @description target path for the redirect */
                    location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    completeSaxoAuthorization: {
        parameters: {
            query?: {
                code?: string | null;
                /** @description State issued by the authorize step. */
                state?: string | null;
                error?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                /** @description State set by the authorize step. */
                rp_saxo_oauth_state?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Redirect Response */
            302: {
                headers: {
                    /** @description target path for the redirect */
                    location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
        };
    };
    connectIbkr: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IbkrConnectRequest"];
            };
        };
        responses: {
            /** @description Connection stored; refresh queued. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionCreatedResponse"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
            /** @description An unexpected server error using the standard API error envelope. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    queueConnectionSync: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connection_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sync queued. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncQueuedResponse"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
            /** @description An unexpected server error using the standard API error envelope. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listTransactions: {
        parameters: {
            query?: {
                page?: number;
                per_page?: number;
                order_by?: string;
                order?: string;
                /** @description Comma-separated ledger kinds. */
                kinds?: string | null;
                portfolio_id?: number | null;
                /** @description Broker account id (PortfolioCard.accounts[].id). */
                account?: number | null;
                /** @description buy, sell or corporate_action; other values are ignored. */
                trade_type?: string | null;
                date_gte?: string | null;
                date_lte?: string | null;
                search?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ledger rows and paging metadata. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionsResponse"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
            /** @description An unexpected server error using the standard API error envelope. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listPositions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Open positions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionsResponse"];
                };
            };
            /** @description An unexpected server error using the standard API error envelope. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getPositionDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                position_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The position. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionDetail"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
            /** @description An unexpected server error using the standard API error envelope. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listPortfolios: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Portfolios in creation order. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfoliosResponse"];
                };
            };
            /** @description An unexpected server error using the standard API error envelope. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updatePortfolio: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortfolioUpdate"];
            };
        };
        responses: {
            /** @description The updated portfolio. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioCard"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
            /** @description An unexpected server error using the standard API error envelope. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listOrders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Orders, working first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrdersResponse"];
                };
            };
            /** @description An unexpected server error using the standard API error envelope. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listCashMovements: {
        parameters: {
            query?: {
                kind?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cash movements, newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CashMovementsResponse"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
            /** @description An unexpected server error using the standard API error envelope. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listPreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Preferences by key. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreferencesResponse"];
                };
            };
            /** @description An unexpected server error using the standard API error envelope. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    savePreference: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreferenceUpdate"];
            };
        };
        responses: {
            /** @description The stored preference. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Preference"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
            /** @description An unexpected server error using the standard API error envelope. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deletePreference: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
            /** @description An unexpected server error using the standard API error envelope. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listPriceStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One row per security. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceStatusResponse"];
                };
            };
            /** @description An unexpected server error using the standard API error envelope. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listDailyPrices: {
        parameters: {
            query: {
                security_id: number;
                date_gte?: string | null;
                date_lte?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bars, oldest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyPricesResponse"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
            /** @description An unexpected server error using the standard API error envelope. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listFxStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One row per (base, currency). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FxStatusResponse"];
                };
            };
            /** @description An unexpected server error using the standard API error envelope. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listFxRates: {
        parameters: {
            query: {
                currency: string;
                base_currency?: string | null;
                date_gte?: string | null;
                date_lte?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rates, oldest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FxSeriesResponse"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
            /** @description An unexpected server error using the standard API error envelope. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stored results or an explicit empty state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardResponse"];
                };
            };
            /** @description An unexpected server error using the standard API error envelope. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listPnlRows: {
        parameters: {
            query?: {
                page?: number;
                per_page?: number;
                order_by?: string;
                order?: string;
                portfolio_id?: number | null;
                security_id?: number | null;
                /** @description security or cash; anything else returns both. */
                position_kind?: string | null;
                /** @description long or short; anything else returns both. */
                position_type?: string | null;
                date_gte?: string | null;
                date_lte?: string | null;
                search?: string | null;
                /** @description Also return days where a position is flat and idle. */
                include_flat?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of attribution rows. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PnlResponse"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
            /** @description An unexpected server error using the standard API error envelope. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listPortfolioDays: {
        parameters: {
            query?: {
                portfolio_id?: number | null;
                date_gte?: string | null;
                date_lte?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Days oldest first with a summary. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioDaysResponse"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
            /** @description An unexpected server error using the standard API error envelope. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listReconciliationIssues: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Issues, newest day first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssuesResponse"];
                };
            };
            /** @description An unexpected server error using the standard API error envelope. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    rebuildPnl: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Row counts per portfolio. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RebuildResponse"];
                };
            };
            /** @description Document created, URL follows */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RebuildResponse"];
                };
            };
            /** @description An unexpected server error using the standard API error envelope. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getReportingCurrency: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current setting and options. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportingCurrencySettings"];
                };
            };
            /** @description An unexpected server error using the standard API error envelope. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    setReportingCurrency: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportingCurrencyUpdate"];
            };
        };
        responses: {
            /** @description Stored; recalculation queued. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportingCurrencySettings"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
            /** @description An unexpected server error using the standard API error envelope. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
